<h2 style="width:100%;background-color:#f00;color:#fff;text-align:center;"><?php echo $this->message?></h2>

<?php if (isset($this->exception)) : ?>

	<h3>Exception information:</h3>
	
	<p><b>Message:</b> <?php echo $this->exception->getMessage()?></p>
	
	<h3>Stack trace:</h3>
	<pre><?php echo $this->exception->getTraceAsString(); ?> </pre>
	
	<h3>Request Parameters:</h3>
	
	<pre><?php echo var_export($this->request->getParams(), true); ?></pre>

<?php endif ?>
