<br />
<h1 style="text-decoration: underline;">Taxon common names query</h1>
<br /><br />
<p>
    Input is a scientific name (a genus name, a species name (binomial) or an infra-species name (trinomial) and the output will be an XML with a list of common names associated with the scientific name.
</p>
<h4>Input URL</h4>
<p>
http://&lt;domain&gt;/common/query/key/&lt;generated_key&gt;/genus/&lt;genus_name&gt;[/species/&lt;species_name&gt;[/infraspecies/&lt;infraspecies_name&gt;]][/version/&lt;version_year&gt;]
</p>
<h4>Parameters</h4>
<ul>
    <li>common - mandatory, service name</li>
    <li>query - mandatory, action name</li>
    <li>key/&lt;generated_key&gt; - mandatory, generated key</li>
    <li>genus/&lt;genus_name&gt; - mandatory</li>
    <li>species/&lt;species_name&gt; - optional</li>
    <li>infraspecies/&lt;infraspecies_name&gt; - optional, requires species parameter</li>
    <li>version/&lt;db_version&gt; - optional, default latest (or last) version.</li>
</ul>
<h4>Examples</h4>
<ul>
    <li>http://&lt;domain&gt;/common/query/key/123456/genus/Tabebuia</li>
    <li>http://&lt;domain&gt;/common/query/key/123456/genus/Salinator/species/solida/version/2011</li>
    <li>http://&lt;domain&gt;/common/query/key/123456/genus/Caryodes/species/dufresnii/infraspecies/superior/version/2011</li>
</ul>

<h4>XML Output</h4>
&lt;?xml version='1.0' encoding='utf-8'?&gt;<br />
&lt;sp2000&gt;<br />
&nbsp;&nbsp;&lt;request&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;service id='common'&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;description&gt;Taxon synonyms in CoL&lt;/description&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;parameters&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;genus&gt;Caryodes&lt;/genus&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;species&gt;dufresnii&lt;/species&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;infraspecies&gt;superior&lt;/infraspecies&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;version&gt;2011&lt;/version&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/parameters&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;date&gt;09 Jun 2021 10:18:14 GMT&lt;/date&gt;<br />
&nbsp;&nbsp;&lt;/request&gt;<br />
&nbsp;&nbsp;&lt;response&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;common id='12344'&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;name&gt;___________&lt;/name&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;language&gt;___________&lt;/language&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;country&gt;___________&lt;/country&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/common&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;...<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;common id=''&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;name&gt;___________&lt;/name&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;language&gt;___________&lt;/language&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;country&gt;___________&lt;/country&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/common&gt;<br />
&nbsp;&nbsp;&lt;/response&gt;<br />
&nbsp;&nbsp;&lt;status code='0'&gt;Success&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='100'&gt;Name not found&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='200'&gt;Unable connect to the specified database&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='300'&gt;Required parameters not specified&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='400'&gt;Unable verify the validity of the key&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='500'&gt;Invalid key&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='600'&gt;[Generic error message]&lt;/status&gt;<br />
&lt;/sp2000&gt;<br />