<?php echo $this->doctype(); ?>

<html>
	<head>
	
		<?php echo $this->headTitle(); ?>
		
		
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		
		<?php echo $this->headLink(); ?>
		
		
		<?php echo $this->headScript(); ?>
		
		
		<script type="text/javascript">
			function baseUrl(target) {
				var base = "<?php echo $this->baseUrl(); ?>";
				if(target[0] == "/") {
					return base + target;
				}
				return base + "/" + target;
			};
			var mvcAaction = "<?php echo Zend_Controller_Front::getInstance()->getRequest()->getActionName()?>";
			var mvcController = "<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName()?>";
			var mvcModule = "<?php echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName()?>";
		</script>
		
	</head>
	<body>
		<div id="eti-main">
		
			<div id="header">
   				<div id="subtitle-left">Catalogue Of Life</div>
    			<h1>
    				<a href="<?php echo $this->baseUrl('/'); ?>">Web Services</a>
    			</h1>
   				<div id="subtitle-right">Catalogue Of Life</div>
   			</div>
			
			<div id="eti-workspace">
				<div class="clear"></div>
				<div id="messages">
					<?php echo $this->messages(); ?>
				</div>
				<div id="eti-content">
					<?php echo $this->layout()->content; ?>	
				</div>
			</div>
			
			<div id="eti-footer"></div>
			
		</div>		
	</body>
</html>