<h2>Welcome</h2>
<p>
	Welcome to the Web Services of the Catalogue of Life. Here you can find
	information on which web services the Catalogue of Life offers, how you can
	subscribe to them, and the technical details of calling the web services from
	within your own application.
</p>

<h2>Subscribing</h2>
<p>
	When calling our web services, your application must provide a key as part
	of the service URL. You can obtain a key by filling out the form below. Anyone
	can make use of the web services provided by the Catalogue of Life. However, we
	reserve the right to suspend, terminate or change the terms of your use of the
	services at any time.
</p>

<p>
	We need at least the domain from which you will be calling our services. The
	key will work for the domain you enter and all its subdomains. You can optionally
	provide us with an email address, so which can inform you about upcoming changes
	in the API, server malfunctions, etc. etc.
</p>

<p>
	<form method="post">
		<table>
			<tbody id="keyform-container">
    			<tr>
    				<td class="right-aligned">Your Domain *</td>
    				<td><input id="domain" type="text" name="domain" value="http://" style="width:300px;" /></td>
    			</tr>
    			<tr>
    				<td class="right-aligned">Your Email</td>
    				<td><input id="email" type="text" name="email" style="width:300px;" /></td>
    			</tr>
    		</tbody>
		</table>
		<div id="button-container0">
			<button type="button" onclick="generateKey();">Generate key</button>
		</div>
	</form>
</p>

<h2>Description of currently available web services</h2>
<h3>Web service 1</h3>
<p>
	Describes web service 1
</p>

<h3>Web service 2</h3>
<p>
	Describes web service 2
</p>

<h3>Web service 3</h3>
<p>
	Describes web service 4
</p>

<h3>Web service 4</h3>
<p>
	Describes web service 4
</p>

