<?php
    function host() {
        echo $_SERVER['HTTP_HOST'];
    }
?>
<h2>Welcome</h2>
<p>
    Welcome to the Web Services of the Catalogue of Life. Here you can find
    information on which web services the Catalogue of Life offers, how you can
    subscribe to them, and the technical details of calling the web services from
    within your own application.
</p>

<h2>Subscribing</h2>
<p>
    Anyone can use our web services, but you have to obtain a key first. You can
    obtain a key by filling out the form below.
    When calling our web services, your application <b>must</b> always include a "key"
    parameter in the request URL. The value of this parameter must be the key that is
    generated for you after you have filled out the form. For example: http://<?php host(); ?>/webservices_v2/synonyms/query/species/panthera/genus/panthera/<b>key/da0ff78ac265d4fa49801b</b>.
</p>

<p>
    We need at least the domain from which you will be calling our services. If you are
    testing the services on your own computer, the IP address we have filled out for you
    is probably OK. Most likely though you will ultimately want to call our services from
    one of your own servers. In that case look up and enter the IP address or domain name
    of that server  The key will work for the domain you enter and all its subdomains. 
    You can optionally provide us with an email address, so we can inform you about 
    upcoming changes in the API, server malfunctions, etc. etc.
</p>

<a name="keyform"></a>
<p>
    <b>Key Request Form</b>
    <form method="post">
        <table>
            <tbody id="keyform-container">
                <tr>
                    <td class="right-aligned">Your Domain <span style="color:#f00;font-weight:bold;">*</span></td>
                    <td><input id="domain" type="text" name="domain" value="<?php echo $_SERVER['REMOTE_ADDR'];?>" style="width:300px;" /></td>
                </tr>
                <tr>
                    <td class="right-aligned">Your Email</td>
                    <td><input id="email" type="text" name="email" style="width:300px;" /></td>
                </tr>
            </tbody>
        </table>
        <div id="button-container0">
            <button type="button" onclick="generateKey();">Generate key</button>
        </div>
    </form>
</p>

<h2>Description of currently available web services</h2>
You can currently call the following services:
<ol>
	<li><a href="#scientific_name_status_web_service">Scientific Name Status web service</a>. Returns the status of a scientific name in the Catalogue of Life</li>
	<li><a href="#synonyms_web_service">Synonyms web service</a>. Returns the synonyms for a scientific name</li>
	<li><a href="#common_names_web_service">Common Names web service</a>. Returns the common names for a scientific name</li>
</ol>
These web services are described in more detail below.
<br/><br/>
<a name="scientific_name_status_web_service"></a>
<h3>Scientific Name Status web service</h3>
<br/><br/>
<p>
    Input is a scientific name (a genus name, a species name (binomial) or an infra-species name (trinomial) and the output is an XML with the status of the provided name in the Catalog of Life and a list of related accepted names with all the available information about each name.
</p>
<h4>Input URL</h4>
<p>
http://<?php host(); ?>/status/query/key/&lt;your-key&gt;/genus/&lt;genus_name&gt;[/species/&lt;species_name&gt;[/infraspecies/&lt;infraspecies_name&gt;]][/version/&lt;version_year&gt;]
</p>
<h4>Parameters</h4>
<ul>
    <li>status - mandatory, service name</li>
    <li>query - mandatory, action name</li>
    <li>key/&lt;your-key&gt; - mandatory, generated key</li>
    <li>genus/&lt;genus_name&gt; - mandatory</li>
    <li>species/&lt;species_name&gt; - optional</li>
    <li>infraspecies/&lt;infraspecies_name&gt; - optional, requires species parameter</li>
    <li>version/&lt;db_version&gt; - optional, default latest (or last) version.</li>	
</ul>
<h4>Examples</h4>
<ul>
    <li>http://<?php host(); ?>/status/query/key/&lt;your-key&gt;/genus/Tabebuia</li>
    <li>http://<?php host(); ?>/status/query/key/&lt;your-key&gt;/genus/Salinator/species/solida/version/2011</li>
    <li>http://<?php host(); ?>/status/query/key/&lt;your-key&gt;/genus/Caryodes/species/dufresnii/infraspecies/superior/version/2011</li>
</ul>

<h4>XML Output</h4>
&lt;?xml version='1.0' encoding='utf-8'?&gt;<br />
&lt;sp2000&gt;<br />
&nbsp;&nbsp;&lt;request&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;service id='status'&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;description&gt;Status of a scientific name in CoL&lt;/description&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;parameters&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;genus&gt;Caryodes&lt;/genus&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;species&gt;dufresnii&lt;/species&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;infraspecies&gt;superior&lt;/infraspecies&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;version&gt;2011&lt;/version&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/parameters&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;date&gt;09 Jun 2021 10:18:14 GMT&lt;/date&gt;<br />
&nbsp;&nbsp;&lt;/request&gt;<br />
&nbsp;&nbsp;&lt;response&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;status&gt;accepted name|ambiguous synonym|misapplied name|privisionally accepted<br /> name|synomym&lt;/status&gt;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;accepted_name id='1221'&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;kingdom&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/kingdom&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;phylum&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/phylum&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;class&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/class&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;order&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/order&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;superfamily&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/superfamily&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;family&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/family&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;genus&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/genus&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;subgenus&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/subgenus&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;species&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/species&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;infraspecies_marker&gt; &nbsp;&nbsp;&nbsp;&nbsp;&lt;/infraspecies_marker&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;infraspecies&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/infraspecies&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;author&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/author&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/accepted_name&gt;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;accepted_name id='1222'&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;kingdom&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/kingdom&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;phylum&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/phylum&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;class&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/class&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;order&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/order&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;superfamily&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/superfamily&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;family&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/family&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;genus&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/genus&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;subgenus&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/subgenus&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;species&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/species&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;infraspecies_marker&gt; &nbsp;&nbsp;&nbsp;&nbsp;&lt;/infraspecies_marker&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;infraspecies&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/infraspecies&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;author&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/author&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/accepted_name&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;<br />
&nbsp;&nbsp;&lt;/response&gt;<br />
&nbsp;&nbsp;&lt;status code='0'&gt;Success&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='100'&gt;Name not found&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='200'&gt;Unable connect to the specified database&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='300'&gt;Required parameters not specified&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='400'&gt;Unable verify the validity of the key&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='500'&gt;Invalid key&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='600'&gt;[Generic error message]&lt;/status&gt;<br />
&lt;/sp2000&gt;<br />
<br /><br />





<a name="synonyms_web_service"></a>
<h3>Synonyms web service</h3>
<br /><br />
<p>
    Input is a scientific name (a genus name, a species name (binomial) or an infra-species name (trinomial) and the output is an XML with the status of the provided name and a list of related Accepted Names with all the information available about each one and a list of all synonyms for each Accepted Name.
</p>
<h4>Input URL</h4>
<p>
http://<?php host(); ?>/synonyms/query/key/&lt;your-key&gt;/genus/&lt;genus_name&gt;[/species/&lt;species_name&gt;[/infraspecies/&lt;infraspecies_name&gt;]][/version/&lt;version_year&gt;]
</p>
<h4>Parameters</h4>
<ul>
    <li>synonyms - mandatory, service name</li>
    <li>query - mandatory, action name</li>
    <li>key/&lt;your-key&gt; - mandatory, generated key</li>
    <li>genus/&lt;genus_name&gt; - mandatory</li>
    <li>species/&lt;species_name&gt; - optional</li>
    <li>infraspecies/&lt;infraspecies_name&gt; - optional, requires species parameter</li>
    <li>version/&lt;db_version&gt; - optional, default latest (or last) version.</li>
</ul>
<h4>Examples</h4>
<ul>
    <li>http://<?php host(); ?>/synonyms/query/key/&lt;your-key&gt;/genus/Tabebuia</li>
    <li>http://<?php host(); ?>/synonyms/query/key/&lt;your-key&gt;/genus/Salinator/species/solida/version/2011</li>
    <li>http://<?php host(); ?>/synonyms/query/key/&lt;your-key&gt;/genus/Caryodes/species/dufresnii/infraspecies/superior/version/2011</li>
</ul>

<h4>XML Output</h4>
&lt;?xml version='1.0' encoding='utf-8'?&gt;<br />
&lt;sp2000&gt;<br />
&nbsp;&nbsp;&lt;request&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;service id='synonyms'&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;description&gt;Taxon synonyms in CoL&lt;/description&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;parameters&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;genus&gt;Caryodes&lt;/genus&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;species&gt;dufresnii&lt;/species&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;infraspecies&gt;superior&lt;/infraspecies&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;version&gt;2011&lt;/version&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/parameters&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;date&gt;09 Jun 2021 10:18:14 GMT&lt;/date&gt;<br />
&nbsp;&nbsp;&lt;/request&gt;<br />
&nbsp;&nbsp;&lt;response&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;accepted_name id='23232'&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;kingdom&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/kingdom&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;phylum&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/phylum&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;class&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/class&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;order&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/order&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;superfamily&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/superfamily&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;family&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/family&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;genus&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/genus&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;subgenus&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/subgenus&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;species&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/species&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;infraspecies_marker&gt; &nbsp;&nbsp;&nbsp;&nbsp;&lt;/infraspecies_marker&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;infraspecies&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/infraspecies&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;author&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/author&gt;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;synonyms&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;synonym id=''&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;status&gt;&lt;/status&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;kingdom&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/kingdom&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;phylum&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/phylum&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;class&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/class&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;order&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/order&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;superfamily&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/superfamily&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;family&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/family&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;genus&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/genus&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;subgenus&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/subgenus&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;species&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/species&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;infraspecies_marker&gt; &nbsp;&nbsp;&nbsp;&nbsp;&lt;/infraspecies_marker&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;infraspecies&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/infraspecies&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;author&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/author&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/synonym&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;synonym id=''&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;status&gt;&lt;/status&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;kingdom&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/kingdom&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;phylum&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/phylum&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;class&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/class&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;order&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/order&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;superfamily&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/superfamily&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;family&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/family&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;genus&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/genus&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;subgenus&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/subgenus&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;species&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/species&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;infraspecies_marker&gt; &nbsp;&nbsp;&nbsp;&nbsp;&lt;/infraspecies_marker&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;infraspecies&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/infraspecies&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;author&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/author&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/synonym&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/synonyms&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/accepted_name&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;<br />
&nbsp;&nbsp;&lt;/response&gt;<br />
&nbsp;&nbsp;&lt;status code='0'&gt;Success&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='100'&gt;Name not found&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='200'&gt;Unable connect to the specified database&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='300'&gt;Required parameters not specified&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='400'&gt;Unable verify the validity of the key&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='500'&gt;Invalid key&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='600'&gt;[Generic error message]&lt;/status&gt;<br />
&lt;/sp2000&gt;<br />
<br /><br />





<a name="common_names_web_service"></a>
<h3>Common Names web service</h3>
<br /><br />
<p>
    Input is a scientific name (a genus name, a species name (binomial) or an infra-species name (trinomial) and the output will be an XML with a list of common names associated with the scientific name.
</p>
<h4>Input URL</h4>
<p>
http://<?php host(); ?>/common/query/key/&lt;your-key&gt;/genus/&lt;genus_name&gt;[/species/&lt;species_name&gt;[/infraspecies/&lt;infraspecies_name&gt;]][/version/&lt;version_year&gt;]
</p>
<h4>Parameters</h4>
<ul>
    <li>common - mandatory, service name</li>
    <li>query - mandatory, action name</li>
    <li>key/&lt;your-key&gt; - mandatory, generated key</li>
    <li>genus/&lt;genus_name&gt; - mandatory</li>
    <li>species/&lt;species_name&gt; - optional</li>
    <li>infraspecies/&lt;infraspecies_name&gt; - optional, requires species parameter</li>
    <li>version/&lt;db_version&gt; - optional, default latest (or last) version.</li>
</ul>
<h4>Examples</h4>
<ul>
    <li>http://<?php host(); ?>/common/query/key/&lt;your-key&gt;/genus/Tabebuia</li>
    <li>http://<?php host(); ?>/common/query/key/&lt;your-key&gt;/genus/Salinator/species/solida/version/2011</li>
    <li>http://<?php host(); ?>/common/query/key/&lt;your-key&gt;/genus/Caryodes/species/dufresnii/infraspecies/superior/version/2011</li>
</ul>

<h4>XML Output</h4>
&lt;?xml version='1.0' encoding='utf-8'?&gt;<br />
&lt;sp2000&gt;<br />
&nbsp;&nbsp;&lt;request&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;service id='common'&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;description&gt;Taxon synonyms in CoL&lt;/description&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;parameters&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;genus&gt;Caryodes&lt;/genus&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;species&gt;dufresnii&lt;/species&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;infraspecies&gt;superior&lt;/infraspecies&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;version&gt;2011&lt;/version&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/parameters&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;date&gt;09 Jun 2021 10:18:14 GMT&lt;/date&gt;<br />
&nbsp;&nbsp;&lt;/request&gt;<br />
&nbsp;&nbsp;&lt;response&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;common id='12344'&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;name&gt;___________&lt;/name&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;language&gt;___________&lt;/language&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;country&gt;___________&lt;/country&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/common&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;...<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;common id=''&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;name&gt;___________&lt;/name&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;language&gt;___________&lt;/language&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;country&gt;___________&lt;/country&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/common&gt;<br />
&nbsp;&nbsp;&lt;/response&gt;<br />
&nbsp;&nbsp;&lt;status code='0'&gt;Success&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='100'&gt;Name not found&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='200'&gt;Unable connect to the specified database&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='300'&gt;Required parameters not specified&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='400'&gt;Unable verify the validity of the key&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='500'&gt;Invalid key&lt;/status&gt;<br />
&nbsp;&nbsp;&lt;status code='600'&gt;[Generic error message]&lt;/status&gt;<br />
&lt;/sp2000&gt;<br />
